### PR TITLE
SRE-28647 Update/Add required labels

### PR DESCRIPTION
**Pull request by mohamedhizaoui-wk**

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by carlbeck-wk — APPROVED** [review]

**Review by andrewrowe-wk — APPROVED** [review]

**Comment by carlbeck-wk** [comment]
@Workiva/release-management-p

**Review by patrickofriel-wk — APPROVED** [review]
+1

**Comment by patrickofriel-wk** [comment]
QA +1

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
