### PR TITLE
RM-35019 RM-35018 CEREBRAL-770 Update alpine

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
Some change randomly broke our builds. This upgrades to recent version of ruby and newer version of alpine.

Reviewers:
@patrickofriel-wk 
@davidgiametta-wk

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by patrickofriel-wk** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Comment by patrickofriel-wk** [comment]
+1

**Pull request merged**
