### PR TITLE
CEREBRAL-1535 Add new path prefix for slate documentation.

### PR DESCRIPTION
**Pull request by davidgiametta-wk**

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by anthonypagnotta-wf** [comment]
+1 SRE

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by anthonypagnotta-wf** [comment]
+1 SRE

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by tylerstapler-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
