### PR TITLE
RM-33539 RM-33538 CEREBRAL-704 Add empty npm.lock to satisify rm.

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
Modifies dockerfile to report dependencies.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by davidgiametta-wk** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Comment by patrickofriel-wk** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Pull request merged**
