### PR TITLE
CEREBRAL-3874 Upgrade npm.

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
###### Overview:
This modifies the build process to grab the latest released version of NPM to make it easier to bring in security fixes.

###### Reviewers:
@Workiva/scout-team

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>activesupport < 5.2.4.3</code> via <code>Gemfile.lock</code></li>
<li>1 vulns in <code>kramdown < 2.3.0</code> via <code>Gemfile.lock</code></li>
<li>2 vulns in <code>rack < 2.1.4</code> via <code>Gemfile.lock</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=slate">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by jessicashelton-wk — APPROVED** [review]

**Review by patrickofriel-wk — APPROVED** [review]
+1

**Review by dougthomas-wk — APPROVED** [review]

**Review by matthewhatch-wk — APPROVED** [review]

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Comment by patrickofriel-wk** [comment]
QA +1

**Pull request merged**
