### PR TITLE
CEREBRAL-1808 Add automatic swagger client generation.

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
Automatically generates client code for go, java, and c#. The python generator is not working correctly, some sort of camel -> snake case conversion issue. I have been able to get that to work correctly with swagger codegen 3+ so I assume it's a 2.x issue. I haven't tested any 3.x clients though so I'd prefer to separate this work as that will require separate verification.

@Workiva/scout-backend

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by patrickofriel-wk** [comment]
+1

**Comment by mattcoleman-wk** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
