### PR TITLE
Release slate 2.2.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pulls Included in Release:
* [Dockerize](https://github.com/Workiva/slate/pull/1)
* [Update with michael changes](https://github.com/Workiva/slate/pull/3)
* [Style update based on UX mock ups](https://github.com/Workiva/slate/pull/4)
* [Add vscode to gitignore.](https://github.com/Workiva/slate/pull/5)
* [Release slate 1.0.1](https://github.com/Workiva/slate/pull/7)
* [Release slate 1.0.2](https://github.com/Workiva/slate/pull/8)

Requested by: @dustinhiatt-wf

Diff Between Last Tag and Proposed Release: N/A
Diff Between Last Tag and New Tag: N/A

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4764903221493760/logs/)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Pull request merged**
