### PR TITLE
CEREBRAL-3939 Consume cerebral v2.38.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Consume [cerebral v2.38.0](https://github.com/Workiva/cerebral/releases/tag/v2.38.0)

Pull Requests included in release:
* Patch changes:
	* [CEREBRAL-3397:  When fetching a query/list of queries, hydrate global parameters](https://github.com/Workiva/cerebral/pull/1732)
	* [CEREBRAL-2454 Expose pivot definition on query dto](https://github.com/Workiva/cerebral/pull/1761)
	* [CEREBRAL-3839 Grand Total for the Percent aggregation types in crosstab queries](https://github.com/Workiva/cerebral/pull/1779)
	* [Cerebral-3806 Add x-return-description tags to all swagger endpoints](https://github.com/Workiva/cerebral/pull/1781)
	* [CEREBRAL-3886 Serialization changes for copy operations](https://github.com/Workiva/cerebral/pull/1784)
	* [Kill old conditional no longer required.](https://github.com/Workiva/cerebral/pull/1785)
	* [Bump app-intelligence from 7.0.1 to 7.0.4](https://github.com/Workiva/cerebral/pull/1787)
	* [Bump spotbugs-maven-plugin from 4.0.0 to 4.0.4](https://github.com/Workiva/cerebral/pull/1788)
	* [Bump DynamoDBLocal from 1.12.0 to 1.13.3](https://github.com/Workiva/cerebral/pull/1789)
	* [CEREBRAL-3843 CEREBRAL-3844 Aggregation Column Grand Total: Max & Min](https://github.com/Workiva/cerebral/pull/1792)
	* [Cerebral-3807 Add example workflow documentation.](https://github.com/Workiva/cerebral/pull/1793)
	* [CEREBRAL-3389 Add global parameters to heimdall models](https://github.com/Workiva/cerebral/pull/1795)
	* [RM-82671 CEREBRAL-3895 Release cerebral v2.38.0](https://github.com/Workiva/cerebral/pull/1797)

@Workiva/release-management-p
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/5039968096878592/logs/)

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>activesupport < 5.2.4.3</code> via <code>Gemfile.lock</code></li>
<li>1 vulns in <code>kramdown < 2.3.0</code> via <code>Gemfile.lock</code></li>
<li>2 vulns in <code>rack < 2.1.4</code> via <code>Gemfile.lock</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=slate">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by patrickofriel-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by patrickofriel-wk** [comment]
@Workiva/release-management-p

**Review by patrickofriel-wk — APPROVED** [review]
+10

**Pull request closed without merging**
