### PR TITLE
CEREBRAL-3723 Check npm version

### PR DESCRIPTION
**Pull request by patrickofriel-wk**
###### Overview:

Add npm version check 

###### Reviewers:
@Workiva/scout-team

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
<details>
<summary>(2) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>activesupport < 5.2.4.3</code> via <code>Gemfile.lock</code></li>
<li>1 vulns in <code>rack < 2.1.4</code> via <code>Gemfile.lock</code></li>
</details>
<details>
<summary>Error scanning for security relevant context</summary>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=slate">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by patrickofriel-wk** [comment]
@aviary-wf

**Comment by patrickofriel-wk** [comment]
@aviary-wf

**Comment by patrickofriel-wk** [comment]
@aviary-wf

**Comment by matthewlorimor-wf** [comment]
@aviary-wf override required

**Comment by matthewlorimor-wf** [comment]
Security +1

**Comment by matthewlorimor-wf** [comment]
@aviary-wf

**Comment by matthewlorimor-wf** [comment]
@aviary-wf

**Comment by patrickofriel-wk** [comment]
QA +1

**Comment by patrickofriel-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
