### PR TITLE
CEREBRAL-4001 Fix up audit during docker build.

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
###### Overview:
We used to have to report an audit document from the build process. That's no longer the case and this is automated.

We don't actually use Ruby in our run build so there's no point in including it there.

###### Reviewers:
@Workiva/scout-team

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>activesupport < 5.2.4.3</code> via <code>Gemfile.lock</code></li>
<li>1 vulns in <code>kramdown < 2.3.0</code> via <code>Gemfile.lock</code></li>
<li>2 vulns in <code>rack < 2.1.4</code> via <code>Gemfile.lock</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=slate">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by dustinhiatt-wf** [comment]
QA +1

**Review by patrickofriel-wk — APPROVED** [review]
+1

**Review by dougthomas-wk — APPROVED** [review]

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
