### PR TITLE
CEREBRAL-1533 Fix up name collision in outline and add link to swagger json.

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
Modifies the `authentication` title in the outline to prevent a collision with the auto generated swagger toc. Also adds a link to swagger ui and our json file.

@davidgiametta-wk 
@mattcoleman-wk

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by mattcoleman-wk** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
QA +1

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Comment by dustinhiatt-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
